services:
  statsvc:
    build: ./statsvc/server
    image: statsvc
    container_name: statsvc
    ports:
      - "9090:9090"
    depends_on:
      statdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    healthcheck:
      test: curl -f http://localhost:9090/actuator/health
      interval: 10s
      timeout: 5s
      retries: 2

  statdb:
    image: postgres:16.1
    container_name: statdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    healthcheck:
      test: pg_isready -q -d statdb -U stat
      interval: 10s
      timeout: 5s
      retries: 2

  mainsvc:
    build: mainsvc
    image: mainsvc
    container_name: mainsvc
    ports:
      - "8080:8080"
    depends_on:
      maindb:
        condition: service_healthy
      statsvc:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://maindb:5432/maindb
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  maindb:
    image: postgres:16.1
    container_name: maindb
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    healthcheck:
      test: pg_isready -q -d maindb -U main
      interval: 10s
      timeout: 5s
      retries: 2