services:
  stats-server:
    build: ./statsvc/server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statdb
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat
    healthcheck:
      test: curl -f http://localhost:9090/actuator/health
      interval: 10s
      timeout: 5s
      retries: 2

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    healthcheck:
      test: pg_isready -q -d statdb -U stat
      interval: 10s
      timeout: 5s
      retries: 2

  ewm-service:
    build: mainsvc
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/maindb
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
    healthcheck:
      test: pg_isready -q -d maindb -U main
      interval: 10s
      timeout: 5s
      retries: 2